Repository IBM/ibm-crossplane-operator, pull requests merged in 2021-08, with the labels that each got.

#39 Fix multiarch catalog builds
  .gitmodules
  Makefile
Labels: approved, size/M

#36 reduce rbac.authorization and CRD permissions
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
  bundle/manifests/shim.bedrock.ibm.com_kafkaclaims.yaml
  bundle/manifests/shim.bedrock.ibm.com_kafkacomposites.yaml
  config/crd/bases/apiextensions.crossplane.io_kafkaclaims.yaml
  config/crd/bases/apiextensions.crossplane.io_kafkacomposites.yaml
  config/crd/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/clusterrole.yaml
Labels: approved, size/XL

#41 add clearing output catalog
  Makefile
Labels: approved, size/XS

#40 Fix automated multiarch builds
  Makefile
Labels: approved, size/M

#43 replace CRD for Kafka in operator
  bundle/manifests/shim.bedrock.ibm.com_kafkaclaims.yaml
  bundle/manifests/shim.bedrock.ibm.com_kafkacomposites.yaml
  config/crd/bases/apiextensions.crossplane.io_kafkaclaims.yaml
  config/crd/bases/apiextensions.crossplane.io_kafkacomposites.yaml
Labels: approved, size/L

#44 add deleted secret permissions from bundle
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
Labels: approved, size/XS

#45 fix image name in csv
  bundle/manifests/shim.bedrock.ibm.com_kafkaclaims.yaml
  bundle/manifests/shim.bedrock.ibm.com_kafkacomposites.yaml
  config/crd/bases/apiextensions.crossplane.io_kafkaclaims.yaml
  config/crd/bases/apiextensions.crossplane.io_kafkacomposites.yaml
Labels: approved, size/S

#46 Change apis from '*.crossplane' to '*.ibm.crossplane'
  bundle.Dockerfile
  bundle/manifests/apiextensions.ibm.crossplane.io_compositeresourcedefinitions.yaml
  bundle/manifests/apiextensions.ibm.crossplane.io_compositions.yaml
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
  bundle/manifests/pkg.ibm.crossplane.io_configurationrevisions.yaml
  bundle/manifests/pkg.ibm.crossplane.io_configurations.yaml
  bundle/manifests/pkg.ibm.crossplane.io_controllerconfigs.yaml
  bundle/manifests/pkg.ibm.crossplane.io_locks.yaml
  bundle/manifests/pkg.ibm.crossplane.io_providerrevisions.yaml
  bundle/manifests/pkg.ibm.crossplane.io_providers.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/apiextensions.ibm.crossplane.io_compositeresourcedefinitions.yaml
  config/crd/bases/apiextensions.ibm.crossplane.io_compositions.yaml
  config/crd/bases/pkg.ibm.crossplane.io_configurationrevisions.yaml
  config/crd/bases/pkg.ibm.crossplane.io_configurations.yaml
  config/crd/bases/pkg.ibm.crossplane.io_controllerconfigs.yaml
  config/crd/bases/pkg.ibm.crossplane.io_locks.yaml
  config/crd/bases/pkg.ibm.crossplane.io_providerrevisions.yaml
  config/crd/bases/pkg.ibm.crossplane.io_providers.yaml
  config/crd/kustomization.yaml
  config/manifests/bases/ibm-crossplane-operator.clusterserviceversion.yaml
  config/rbac/clusterrole.yaml
Labels: approved, size/L

#48 releatedImage
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
  common/scripts/adjust_manifests.sh
Labels: approved, size/S

#49 fix display name csv
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-crossplane-operator.clusterserviceversion.yaml
Labels: approved, size/XS

#50 add commonLabel
  bundle/manifests/apiextensions.ibm.crossplane.io_compositeresourcedefinitions.yaml
  bundle/manifests/apiextensions.ibm.crossplane.io_compositions.yaml
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
  bundle/manifests/pkg.ibm.crossplane.io_configurationrevisions.yaml
  bundle/manifests/pkg.ibm.crossplane.io_configurations.yaml
  bundle/manifests/pkg.ibm.crossplane.io_controllerconfigs.yaml
  bundle/manifests/pkg.ibm.crossplane.io_locks.yaml
  bundle/manifests/pkg.ibm.crossplane.io_providerrevisions.yaml
  bundle/manifests/pkg.ibm.crossplane.io_providers.yaml
  bundle/manifests/shim.bedrock.ibm.com_kafkaclaims.yaml
  bundle/manifests/shim.bedrock.ibm.com_kafkacomposites.yaml
  config/crd/kustomization.yaml
  config/manifests/bases/ibm-crossplane-operator.clusterserviceversion.yaml
Labels: approved, size/M

#52 remove * sign from rbac permissions
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
  config/crd/bases/shim.bedrock.ibm.com_kafkaclaims.yaml
  config/crd/bases/shim.bedrock.ibm.com_kafkacomposites.yaml
  config/crd/kustomization.yaml
  config/rbac/clusterrole.yaml
Labels: approved, size/S

#53 fix image name
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-crossplane-operator.clusterserviceversion.yaml
Labels: approved, size/XS

#54 Change POD_NAMESPACE to WATCH_NAMESPACE
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, size/S

#55 Add resources to clusterrole
  config/rbac/clusterrole.yaml
Labels: approved, size/XS

#57 Update clusterrole
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
  config/rbac/clusterrole.yaml
Labels: approved, size/M

#64 Bundle tests
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
  common/scripts/lint-csv.sh
  config/samples/apiextensions.ibm.crossplane.io_compositeresourcedefinition.yaml
  config/samples/kustomization.yaml
Labels: approved, size/M
