Repository IBM/ibm-crossplane-operator, pull requests merged in 2021-09, with the labels that each got.

#69 Update CSV
  bundle/manifests/apiextensions.ibm.crossplane.io_compositions.yaml
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
  bundle/manifests/pkg.ibm.crossplane.io_configurationrevisions.yaml
  bundle/manifests/pkg.ibm.crossplane.io_controllerconfigs.yaml
  bundle/manifests/pkg.ibm.crossplane.io_providerrevisions.yaml
Labels: approved, size/L

#71 remove cluster permissions for secrets
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
  config/rbac/clusterrole.yaml
Labels: approved, size/S

#72 enable 'replaces' section update via script
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
  common/scripts/adjust_manifests.sh
Labels: approved, size/XS

#75 update configuration and operator image to 1.1.0
  config/manager/manager.yaml
Labels: approved, size/XS

#80 Update rbac
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: approved, size/S
