Repository IBM/ibm-crossplane-operator, pull requests merged in 2021-12, with the labels that each got.

#100 fix indent changes in CSV
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
Labels: approved, size/XXL

#101 add lables to rbac for provider
  bundle/manifests/ibm-crossplane-provider-kubernetes_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/ibm-crossplane-provider-kubernetes_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/ibm-crossplane-provider-kubernetes_rbac.authorization.k8s.io_v1_role.yaml
  bundle/manifests/ibm-crossplane-provider-kubernetes_rbac.authorization.k8s.io_v1_rolebinding.yaml
  config/rbac/provider_kubernetes_clusterrole.yaml
  config/rbac/provider_kubernetes_clusterrole_binding.yaml
  config/rbac/provider_kubernetes_role.yaml
  config/rbac/provider_kubernetes_role_binding.yaml
Labels: approved, size/M

#104 revert git submodule update --init
  Makefile
Labels: approved, size/XS

#107 Update build_catsrc.sh script to switch provider images
  common/scripts/build_catsrc.sh
Labels: approved, size/XS
