Repository IBM/ibm-crossplane-operator, pull requests merged in 2021-07, with the labels that each got.

#11 to cd
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-crossplane-operator.clusterserviceversion.yaml
Labels: approved

#12 packagePullPolicy Always
  helm-charts/ibm-crossplane/templates/configuration.yaml
Labels: approved, size/XS

#17 Github action building catsrc + fixes
  .github/workflows/catsrc.yaml
  .gitignore
  common/scripts/build_catsrc.sh
  common/scripts/install_tools.sh
Labels: approved, size/XL

#18 Add manual for building & installing catalog source
  .github/workflows/catsrc.yaml
  CATSRC.md
  common/scripts/build_catsrc.sh
  common/scripts/update_global_pull_secrets.sh
Labels: approved, size/M

#19 Ppytel
  Dockerfile
  Makefile
  build/entrypoint
  build/user_setup
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
  bundle/manifests/pkg.ibm.crossplane.io_configurations.yaml
  config/crd/bases/pkg.ibm.crossplane.io_configurations.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-crossplane-operator.clusterserviceversion.yaml
  config/rbac/clusterrole.yaml
Labels: approved, size/L

#20 remove helm chart files
  PROJECT
  watches.yaml
Labels: approved, size/S

#21 Reduce size
  Dockerfile
  build/entrypoint
Labels: approved, size/XS

#26 Ppytel2
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  Makefile
  README.md
  common/scripts/adjust_manifests.sh
  config/manifests/bases/ibm-crossplane-operator.clusterserviceversion.yaml
Labels: approved, size/L

#25 Build missing images for catsrc
  .github/workflows/catsrc.yaml
  CATSRC.md
  Makefile
  common/scripts/build_catsrc.sh
  common/scripts/install_tools.sh
Labels: approved, size/L

#28 Update catsrc items
  .github/workflows/catsrc.yaml
  .gitignore
  Makefile
  common/scripts/build_catsrc.sh
Labels: approved, size/L

#29 fix passing args to container
  Dockerfile
  build/entrypoint
Labels: approved, size/XS

#27 Image tags with git version hash
  Makefile
  common/scripts/build_catsrc.sh
Labels: approved, size/S

#30 fix make images
  Makefile
Labels: approved, size/S

#32 fix operator name
  Makefile
Labels: approved, size/S

#33 fix sub module
  Makefile
Labels: approved, size/XS

#34 Update instal_tools.sh to always use yq 3.4.1
  common/scripts/install_tools.sh
Labels: approved, size/S
