Repository IBM/ibm-crossplane-operator, pull requests merged in 2022-02, with the labels that each got.

#123 Add Upgrade description to README.md
  README.md
Labels: approved, size/XS

#124 add provider label to configuration sample
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
  config/samples/pkg.ibm.crossplane.io_configuration.yaml
Labels: approved, size/XS

#126 Update release verison
  PREVIOUS_VERSION
  README.md
  RELEASE_VERSION
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-crossplane-operator.clusterserviceversion.yaml
  config/samples/pkg.ibm.crossplane.io_configurationrevision.yaml
Labels: approved, size/M

#128 recreate configmap
  bundle/manifests/crossplane-config_v1_configmap.yaml
  config/configmap/config.yaml
Labels: approved, size/XS

#130 revert permissions for Objects
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
  config/rbac/clusterrole.yaml
Labels: approved, size/XS

#131 update release version
  PREVIOUS_VERSION
  README.md
  RELEASE_VERSION
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-crossplane-operator.clusterserviceversion.yaml
  config/samples/pkg.ibm.crossplane.io_configurationrevision.yaml
Labels: size/M, lgtm

#132 fix for OperandRequest
  bundle/manifests/crossplane-config_v1_configmap.yaml
  config/configmap/config.yaml
Labels: approved, size/XS

#133 update go to version 1.17.7
  .github/workflows/catsrc.yaml
Labels: size/XS
