Repository IBM/ibm-crossplane-operator, pull requests merged in 2022-01, with the labels that each got.

#109 CatalogSource with Providers
  .github/workflows/catsrc.yaml
  CATSRC.md
  common/scripts/build_catsrc.sh
Labels: approved, size/M

#110 fix files with old version
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-crossplane-operator.clusterserviceversion.yaml
  config/samples/pkg.ibm.crossplane.io_configuration.yaml
  config/samples/pkg.ibm.crossplane.io_configurationrevision.yaml
Labels: approved, size/S

#111 Remove premissions for kubernetes.crossplane.io/Objects
  config/rbac/clusterrole.yaml
Labels: approved, size/XS

#112 fix csv
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
Labels: approved, size/XS

#113 Fix catsrc action
  common/scripts/build_catsrc.sh
Labels: approved, size/XS

#114 fix package names in build_catsrc.sh
  common/scripts/build_catsrc.sh
Labels: approved, size/XS

#115 IKS installation script
  hack/install_crossplane.sh
Labels: approved, size/M

#116 Fix IKS install script
  hack/install_crossplane.sh
Labels: approved, size/S

#118 yq4 support for installation script
  hack/install_crossplane.sh
Labels: approved, size/S

#121 fix for reading data from configuration image
  .gitignore
  Makefile
  bundle/manifests/crossplane-config_v1_configmap.yaml
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
  common/scripts/build_catsrc.sh
  config/configmap/config.yaml
  config/configmap/kustomization.yaml
  config/default/kustomization.yaml
  config/manager/manager.yaml
Labels: approved, size/L

#122 fix sample of Configuration
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
  config/samples/pkg.ibm.crossplane.io_configuration.yaml
Labels: approved, size/XS
