Repository IBM/ibm-crossplane-operator, pull requests merged in 2022-11, with the labels that each got.

#162 bump ltsr version
  PREVIOUS_VERSION
  README.md
  RELEASE_VERSION
  bundle/manifests/ibm-crossplane-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-crossplane-operator.clusterserviceversion.yaml
  config/samples/pkg.ibm.crossplane.io_configurationrevision.yaml
Labels: approved, size/M

#163 New prow cluster name
  Makefile
  common/Makefile.common.mk
Labels: size/XS, lgtm

#164 New prow cluster name
  common/Makefile.common.mk
Labels: size/XS
